print("Hello, my name is XeoBot!")
print("Please fill out the following information:")
name = input("Enter your name: ")
print(f"Welcome, {name}")
color = input("What is your favorite color? ")
print(f"{color} is a nice color!")
age = input("How old are you? ")
xeobot_age = 12
age_difference = int(age) - xeobot_age
print(f"You are {age} years old! I am {xeobot_age} years old, so you are {age_difference} years older than me!")
hobby = input("What is your favorite hobby? ")
print(f"{hobby}! That sounds fun!")
print("Thank you for participating in this survey!")
print("I hope you have a great day!")
print("Goodbye!")
print("This program was created by XeoBot.")
print("If you have any questions, feel free to ask!")
print("This program is designed to collect basic information about you.")
print("It is not intended to collect any sensitive information.")
print("Please do not share any personal information that you are not comfortable with.")
input("Press Enter to exit the program...")